import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { ClientApp } from "./ClientApp";

const lato = Lato({ subsets: ["latin"], weight: ["300"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ClientApp>{children}</ClientApp>
      </body>
    </html>
  );
}
